# Generated by Django 4.2.18 on 2025-01-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_propertytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='property_type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_purchase', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], max_length=10)),
                ('number_of_beds', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.FloatField()),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.features')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.propertytype')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.view')),
            ],
        ),
    ]
